{% set version = "0.0.7" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-als
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/ALS_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/ALS/ALS_{{ version }}.tar.gz
  sha256: 57a195e8c5a3d856cd543c99ae532cc25c83b3b444f513b74447bf4a72378da0

build:
  merge_build_host: true  # [win]
  number: 1
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-iso
    - r-nnls >=1.1
  run:
    - r-base
    - r-iso
    - r-nnls >=1.1

test:
  commands:
    - $R -e "library('ALS')"           # [not win]
    - "\"%R%\" -e \"library('ALS')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=ALS
  license: GPL-2.0-or-later
  summary: Alternating least squares is often used to resolve components contributing to data with a bilinear structure; the basic technique may be extended to alternating constrained least squares.  Commonly applied constraints include unimodality, non-negativity, and normalization of components. Several data matrices may
    be decomposed simultaneously by assuming that one of the two matrices in the bilinear decomposition is shared between datasets.
  license_family: GPL3
  license_file: {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: ALS
# Type: Package
# Title: Multivariate Curve Resolution Alternating Least Squares (MCR-ALS)
# Version: 0.0.6
# Author: Katharine M. Mullen
# Maintainer: Katharine Mullen <mullenkate@gmail.com>
# Depends: nnls (>= 1.1), Iso, R (>= 2.10)
# Description: Alternating least squares is often used to resolve components contributing to data with a bilinear structure; the basic technique may be extended to alternating constrained least squares.  Commonly applied constraints include unimodality, non-negativity, and normalization of components. Several data matrices may be decomposed simultaneously by assuming that one of the two matrices in the bilinear decomposition is shared between datasets.
# License: GPL (>= 2)
# Packaged: 2015-08-03 07:12:50 UTC; kmm
# Repository: CRAN
# Date/Publication: 2015-08-03 11:44:35
# NeedsCompilation: no
