appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: AFihTDyMhNXkhCRoWeIO0jedSRzVLa/pGTSRamsrZcA5uMKY3VePuX1Mx7BnePVVK/jOMhYzbC/YzY+QLTs1D/e46A7Sy2q6I8y5jwW3X3Fi7ho0rjq7BE8OakEi1KCnkKJwhh/lg2CeEDYBs1ARDRmusZCPvtVg/M7lU/Z2o4bTUdvknwHkVCHMg2J5XKskoka2pOK47cunICNbla2X9svUuScKmy3e2LfJ0EKjVOUr/Eetcf83bkCgvgZgQ4gihnKrQ4qiG3pdHcZjZJVHyPnrLa0cq31+RhsNbf3BlLSwtmTwxtUbth1AGazihhtIoo97xrBdlbgVW1AEeF4wLw5SjpAQ3kF+RjxcUE97sM3BVtpOzqMB/O/1hsT8Lbi24EwHw9giSLLRojjPF1bmNsLnyNC5oH4tnRli0F/TfvqBQDUh6Rx7rRKqmhPm7YUd4/ihcyIqpGgJE+DATcvgpiTIc5Kpmb4bukwgTVgCigGC8HcZYsClsIbwycmFXZu72cVsf72Z0Xo2o+thvvc+XSRWowRD4XXWR16JGgcGmwS24VNCDS6FS0babXpq+LlGcitz7prxy5BbD/4GcTb5u1kWEtd/f/S9QkbEgBp1Zq8xTq6JcNOQlNSDK9PMaXelAmyXKiyEL4+VyzRnygZR+DCczsIj5BLnz3pvCp6Adrk=
